name: FastAPI Docker CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: persimmon-ai       # your GCP project ID
  REGION: asia-south1            # GCP region
  REPO_NAME: persimmon-app-dev   # Docker/Artifact Registry repo name
  IMAGE_NAME: fastapi-app        # Docker image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      # 4. Run tests (optional)
      - name: Run tests
        run: |
          pytest || echo "No tests found"

      # 5. Lint code (optional)
      - name: Lint with flake8
        run: flake8 . --max-line-length=100 || true

      # 6. Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      # 7. Configure Docker for GCR
      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # 8. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA .

      # 9. Push Docker image
      - name: Push Docker image to GCR
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
