name: Build & Push Docker Image to GCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # manual trigger

env:
  PROJECT_ID: your-gcp-project-id       # replace with your GCP project ID
  REGION: asia-south1                   # GCP region (same as your Artifact Registry)
  REPO_NAME: docker-repo                # Artifact Registry repository
  IMAGE_NAME: fastapi-app               # Docker image name

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use GCP Artifact Registry
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # Push Docker image to GCR
      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
